name: deploy-client

on:
  push:
    branches: 
      - master
    paths: 
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t chamika/client .
      - run: docker login -u $DOCKER_HUB_USER_NAME -p $DOCKER_HUB_PASSWORD
        env:
          DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker push chamika/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DITIGALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment client-depl
